# Site settings
title: Instinctive Programmer
email: vaibhavkhunger@gmail.com
description: > 
  InstinctiveProgrammer is a platform to share my hacks & spikes 
  with the world, through blog posts. Here you will find posts mostly related 
  to BigData & Data Parallelism (my area of interest).

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://instinctiveprogrammer.github.io/" # the base hostname & protocol for your site
twitter_username: vaibhavkhunger
github_username:  vaibhavkhunger

# Build settings
markdown: kramdown
timezone: Asia/Kolkata
